package com.poyo.ow.Models

data class CareerStats(
    val allHeroes: AllHeroes,
    val ana: Ana,
    val ashe: Ashe,
    val baptiste: Baptiste,
    val bastion: Bastion,
    val brigitte: Brigitte,
    val dVa: DVa,
    val doomfist: Doomfist,
    val echo: Echo,
    val genji: Genji,
    val hanzo: Hanzo,
    val junkrat: Junkrat,
    val lucio: Lucio,
    val mccree: Mccree,
    val mei: Mei,
    val mercy: Mercy,
    val moira: Moira,
    val orisa: Orisa,
    val pharah: Pharah,
    val reaper: Reaper,
    val reinhardt: Reinhardt,
    val roadhog: Roadhog,
    val sigma: Sigma,
    val soldier76: Soldier76,
    val sombra: Sombra,
    val symmetra: Symmetra,
    val torbjorn: Torbjorn,
    val tracer: Tracer,
    val widowmaker: Widowmaker,
    val winston: Winston,
    val wreckingBall: WreckingBall,
    val zarya: Zarya,
    val zenyatta: Zenyatta
)