package com.poyo.ow.Models

data class CareerStatsX(
    val allHeroes: AllHeroesX,
    val ana: AnaXX,
    val ashe: AsheXX,
    val baptiste: BaptisteXX,
    val bastion: BastionXX,
    val brigitte: BrigitteXX,
    val dVa: DVaXX,
    val doomfist: Doomfist? = null,
    val echo: Echo,
    val genji: GenjiXX,
    val hanzo: HanzoXX,
    val junkrat: JunkratXX,
    val lucio: LucioXX,
    val mccree: MccreeXX,
    val mercy: MercyXX,
    val moira: MoiraXX,
    val orisa: OrisaXX,
    val pharah: PharahXX,
    val reaper: ReaperXX,
    val reinhardt: ReinhardtXX,
    val roadhog: RoadhogXX,
    val sigma: SigmaXX,
    val soldier76: Soldier76XX,
    val sombra: SombraXX,
    val torbjorn: TorbjornXX,
    val tracer: TracerXX,
    val widowmaker: WidowmakerXX,
    val winston: WinstonXX,
    val wreckingBall: WreckingBallXX,
    val zarya: ZaryaXX,
    val zenyatta: ZenyattaXX
)