package com.poyo.ow.Models

data class LucioXX(
    //val assists: AssistsXXXXXXXXXXXXXXXXXXXXXX,
    //val average: AverageXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val best: BestXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val combat: CombatXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,

    val game: GameXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val heroSpecific: HeroSpecificXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val matchAwards: MatchAwardsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val miscellaneous: Any
)