package com.poyo.ow.Models

data class MccreeXX(
    //val assists: Any,
    //val average: AverageXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val best: BestXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val combat: CombatXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,

    val game: GameXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val heroSpecific: HeroSpecificXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val matchAwards: MatchAwardsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val miscellaneous: MiscellaneousXXXXXXXXXXXXXXXXXXXXXXX
)