package com.poyo.ow.Models

data class TopHeroes(
    val ana: AnaX? = null,
    val ashe: AsheX? = null,
    val baptiste: BaptisteX? = null,
    val bastion: BastionX? = null,
    val brigitte: BrigitteX? = null,
    val dVa: DVaX? = null,
    val doomfist: DoomfistX? = null,
    val echo: EchoX? = null,
    val genji: GenjiX? = null,
    val hanzo: HanzoX? = null,
    val junkrat: JunkratX? = null,
    val lucio: LucioX? = null,
    val mccree: MccreeX? = null,
    val mei: MeiX? = null,
    val mercy: MercyX? = null,
    val moira: MoiraX? = null,
    val orisa: OrisaX? = null,
    val pharah: PharahX? = null,
    val reaper: ReaperX? = null,
    val reinhardt: ReinhardtX? = null,
    val roadhog: RoadhogX? = null,
    val sigma: SigmaX? = null,
    val soldier76: Soldier76X? = null,
    val sombra: SombraX? = null,
    val symmetra: SymmetraX? = null,
    val torbjorn: TorbjornX? = null,
    val tracer: TracerX? = null,
    val widowmaker: WidowmakerX? = null,
    val winston: WinstonX? = null,
    val wreckingBall: WreckingBallX? = null,
    val zarya: ZaryaX? = null,
    val zenyatta: ZenyattaX? = null
)