package com.poyo.ow.Models

data class TopHeroesX(
    val ana: AnaXXX? = null,
    val ashe: AsheXXX? = null,
    val baptiste: BaptisteXXX? = null,
    val bastion: BastionXXX? = null,
    val brigitte: BrigitteXXX? = null,
    val dVa: DVaXXX? = null,
    val doomfist: DoomfistX? = null,
    val echo: EchoX? = null,
    val genji: GenjiXXX? = null,
    val hanzo: HanzoXXX? = null,
    val junkrat: JunkratXXX? = null,
    val lucio: LucioXXX? = null,
    val mccree: MccreeXXX? = null,
    val mercy: MercyXXX? = null,
    val moira: MoiraXXX? = null,
    val orisa: OrisaXXX? = null,
    val pharah: PharahXXX? = null,
    val reaper: ReaperXXX? = null,
    val reinhardt: ReinhardtXXX? = null,
    val roadhog: RoadhogXXX? = null,
    val sigma: SigmaXXX? = null,
    val soldier76: Soldier76XXX? = null,
    val sombra: SombraXXX? = null,
    val torbjorn: TorbjornXXX? = null,
    val tracer: TracerXXX? = null,
    val widowmaker: WidowmakerXXX? = null,
    val winston: WinstonXXX? = null,
    val wreckingBall: WreckingBallXXX? = null,
    val zarya: ZaryaXXX? = null,
    val zenyatta: ZenyattaXXX? = null
)