package com.poyo.ow.Models

data class WidowmakerXX(
    //val assists: AssistsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val average: AverageXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val best: BestXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val combat: CombatXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,

    val game: GameXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val heroSpecific: HeroSpecificXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    val matchAwards: MatchAwardsXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,
    //val miscellaneous: Any
)